import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Providers from "./providers";
import Sidebar from "@/features/sidebar/sidebar";
import cn from "@/utils/cn";
import "@/styles/globals.css";

const font = Kanit({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Template",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    font.className,
                    "bg-slate-950 text-white antialiased",
                )}
            >
                <Providers>
                    <div className="h-screen grid grid-cols-[200px_1fr] overflow-hidden">
                        <Sidebar />
                        <div className="overflow-y-auto">{children}</div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
