import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Component List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-[200px_1fr] h-screen">
          <div className="border-r flex flex-col gap-4 h-screen">
            <h1 className="font-bold p-4 ">Components</h1>
            <div className="overflow-y-auto h-full">
              <ul className="[&>*]:h-[30vh] [&>*]:border">
                <li>
                  <Link href="#123">123</Link>
                </li>
                <li>
                  <Link href="#123">123</Link>
                </li>
                <li>
                  <Link href="#123">123</Link>
                </li>
                <li>
                  <Link href="#123">123</Link>
                </li>
                <li>
                  <Link href="#123">123</Link>
                </li>
                <li>
                  <Link href="#123">123</Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="bg-grey-light overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
